---

service: route53-upsert
frameworkVersion: ">=2"

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "route53:ChangeResourceRecordSets"
      Resource:
        - "*"
#      Condition:
#        ArnEquals:
#          "aws:SourceArn": "arn:aws:route53:::hostedzone/${env:HOSTED_ZONE_ID}"

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: main.app

plugins:
  - serverless-python-requirements
  - serverless-wsgi

